"""Optional PyDy adapter for advanced validation/simulation workflows.

PyDy remains an adapter, not the default student solver. This module exposes
two layers:

1. Always-available symbolic blueprints generated by SymPy Mechanics.
2. Optional PyDy System construction when PyDy is installed in the environment.

The normal DynaTutor app must continue to work when PyDy is unavailable.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

from engine.adapters.sympy_mechanics_adapter import derive_model, list_mechanics_models


@dataclass
class PyDyUseCase:
    name: str
    purpose: str
    realtime_safe: bool = False


@dataclass
class PyDyAdapterStatus:
    available: bool
    version: str | None
    message: str


@dataclass
class PyDyBlueprint:
    name: str
    pydy_available: bool
    realtime_safe: bool
    coordinates: list[str]
    speeds: list[str]
    equations: list[str]
    mass_matrix: list[list[str]]
    forcing: list[str]
    suggested_use: str
    warnings: list[str]

    def to_dict(self) -> dict:
        return asdict(self)


SUPPORTED_USE_CASES = [
    PyDyUseCase("simple_pendulum", "equation generation example"),
    PyDyUseCase("mass_spring_damper", "ODE simulation example"),
    PyDyUseCase("particle_on_rotating_rod", "Coriolis/rotating-frame validation"),
    PyDyUseCase("planar_rigid_body_rotation", "advanced rigid-body equation generation"),
    PyDyUseCase("connected_particles_spring", "coupled particle system scaffold"),
]


def get_pydy_status() -> PyDyAdapterStatus:
    try:
        import pydy  # type: ignore
        version = getattr(pydy, "__version__", None)
        return PyDyAdapterStatus(True, version, "PyDy is importable.")
    except Exception as exc:
        return PyDyAdapterStatus(False, None, f"PyDy is not importable in this runtime: {exc}")


def list_supported_use_cases() -> list[dict]:
    return [u.__dict__ for u in SUPPORTED_USE_CASES]


def build_pydy_blueprint(name: str) -> PyDyBlueprint:
    derivation = derive_model(name)
    status = get_pydy_status()
    return PyDyBlueprint(
        name=derivation.name,
        pydy_available=status.available,
        realtime_safe=False,
        coordinates=derivation.coordinates,
        speeds=derivation.speeds,
        equations=derivation.equations,
        mass_matrix=derivation.mass_matrix,
        forcing=derivation.forcing,
        suggested_use="offline validation / future simulation adapter",
        warnings=[
            "Do not call PyDy in the normal student solve path.",
            "Use this blueprint to compare generated equations or build offline simulations.",
            status.message,
        ],
    )


def build_optional_pydy_system(name: str) -> dict[str, Any]:
    """Attempt to create a PyDy System-like payload.

    This function intentionally returns a serializable dict instead of forcing
    a live System into normal app state. If PyDy is not installed, the returned
    payload still contains the symbolic derivation blueprint.
    """
    blueprint = build_pydy_blueprint(name)
    status = get_pydy_status()

    if not status.available:
        return {
            "ok": False,
            "reason": status.message,
            "blueprint": blueprint.to_dict(),
        }

    try:
        # Keep this import local so normal runtime does not require PyDy import.
        from pydy.system import System  # type: ignore  # noqa: F401

        return {
            "ok": True,
            "reason": "PyDy is available. Use the symbolic blueprint to construct a System with numerical constants and initial conditions.",
            "blueprint": blueprint.to_dict(),
            "system_class": "pydy.system.System",
        }
    except Exception as exc:
        return {
            "ok": False,
            "reason": f"PyDy import succeeded, but System setup failed or is unavailable: {exc}",
            "blueprint": blueprint.to_dict(),
        }


def list_adapter_models() -> list[dict[str, Any]]:
    models = list_mechanics_models()
    status = get_pydy_status()
    return [{**m, "pydy_available": status.available, "realtime_safe": False} for m in models]
